//! Jira → code scaffold.
//!
//! Input: an English "I want to build X" idea plus a Jira project key and a
//! local target directory. Output: a Jira epic, 3-5 stories, a scaffold folder
//! with a README/CLAUDE.md/src/main.rs, a git branch, and a first commit —
//! all chained so Chris goes from idea to ready-to-code branch in one shot.

use std::path::{Path, PathBuf};

use async_trait::async_trait;
use serde_json::Value;
use tokio::process::Command;

use crate::error::{Error, Result};
use super::jira::JiraClient;
use super::{Tool, ToolResult, ToolSchema};

pub struct Scaffold {
    pub jira: Option<JiraClient>,
}

#[async_trait]
impl Tool for Scaffold {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "scaffold_idea".into(),
            description: "Turn an English idea into Jira epic+stories + local git branch + starter folder + first commit. Use when Chris says 'I want to build X' or '/scaffold'.".into(),
            parameters: serde_json::json!({
                "type":"object",
                "properties":{
                    "idea":{"type":"string","description":"What to build, in English"},
                    "project_key":{"type":"string","description":"Jira project key, e.g. FLACO"},
                    "target_dir":{"type":"string","description":"Parent dir for the new scaffold, default ~/Documents/dev"},
                    "branch":{"type":"string","description":"Git branch name, default feature/<slug>"},
                    "stories":{"type":"array","items":{"type":"string"},"description":"Optional pre-broken-down story list"}
                },
                "required":["idea","project_key"]
            }),
        }
    }

    async fn call(&self, args: Value) -> Result<ToolResult> {
        let idea = args.get("idea").and_then(Value::as_str).unwrap_or("").trim().to_string();
        if idea.is_empty() { return Ok(ToolResult::err("idea required")); }
        let project_key = args.get("project_key").and_then(Value::as_str).unwrap_or("FLACO").to_string();
        let target_parent = args
            .get("target_dir")
            .and_then(Value::as_str)
            .map(PathBuf::from)
            .unwrap_or_else(|| {
                std::env::var_os("HOME")
                    .map(PathBuf::from)
                    .unwrap_or_else(|| PathBuf::from("/tmp"))
                    .join("Documents/dev")
            });

        let slug = slugify(&idea);
        let branch = args
            .get("branch")
            .and_then(Value::as_str)
            .map(str::to_string)
            .unwrap_or_else(|| format!("feature/{slug}"));

        let scaffold_dir = target_parent.join(&slug);
        tokio::fs::create_dir_all(scaffold_dir.join("src")).await?;

        // Write README + CLAUDE.md + a starter main.rs.
        tokio::fs::write(
            scaffold_dir.join("README.md"),
            format!("# {slug}\n\n{idea}\n\nGenerated by flaco scaffold on {}.\n",
                chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")),
        )
        .await?;
        tokio::fs::write(
            scaffold_dir.join("CLAUDE.md"),
            format!("# Context for {slug}\n\n## Goal\n{idea}\n\n## Conventions\n- Small commits.\n- Tests required before merge.\n- Local AI only (Ollama).\n"),
        )
        .await?;
        tokio::fs::write(
            scaffold_dir.join("src/main.rs"),
            "fn main() {\n    println!(\"hello from flaco scaffold\");\n}\n",
        )
        .await?;
        tokio::fs::write(
            scaffold_dir.join("Cargo.toml"),
            format!("[package]\nname = \"{slug}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n"),
        )
        .await?;

        // git init + branch + first commit
        run_git(&scaffold_dir, &["init", "-q"]).await?;
        run_git(&scaffold_dir, &["checkout", "-q", "-b", &branch]).await.ok();
        run_git(&scaffold_dir, &["add", "."]).await?;
        run_git(
            &scaffold_dir,
            &["commit", "-q", "--no-verify", "-m", &format!("scaffold: {idea}")],
        )
        .await
        .ok();

        // Jira epic + stories
        let mut jira_lines: Vec<String> = Vec::new();
        let mut jira_json = serde_json::json!({ "created": [] });
        if let Some(jira) = &self.jira {
            let epic_title = format!("Epic: {}", truncate_title(&idea, 120));
            let epic = jira
                .create_issue(&project_key, &epic_title, &idea, "Epic")
                .await;
            match epic {
                Ok(e) => {
                    let key = e.get("key").and_then(Value::as_str).unwrap_or("?");
                    jira_lines.push(format!("Epic {key}: {epic_title}"));
                    if let Some(arr) = jira_json.get_mut("created").and_then(Value::as_array_mut) {
                        arr.push(e);
                    }
                    let stories = args
                        .get("stories")
                        .and_then(Value::as_array)
                        .cloned()
                        .unwrap_or_else(|| default_stories(&idea));
                    for story in stories.iter().take(5) {
                        let summary = story.as_str().unwrap_or("").trim();
                        if summary.is_empty() { continue; }
                        match jira
                            .create_issue(
                                &project_key,
                                summary,
                                &format!("Part of: {idea}"),
                                "Task",
                            )
                            .await
                        {
                            Ok(s) => {
                                let k = s.get("key").and_then(Value::as_str).unwrap_or("?");
                                jira_lines.push(format!("  ↳ {k}: {summary}"));
                                if let Some(arr) = jira_json.get_mut("created").and_then(Value::as_array_mut) {
                                    arr.push(s);
                                }
                            }
                            Err(e) => {
                                jira_lines.push(format!("  ↳ (failed to create '{summary}': {e})"));
                            }
                        }
                    }
                }
                Err(e) => jira_lines.push(format!("(Jira epic create failed: {e})")),
            }
        } else {
            jira_lines.push("(Jira client not configured — skipped)".into());
        }

        let mut summary = String::new();
        summary.push_str(&format!("✓ scaffold at {}\n", scaffold_dir.display()));
        summary.push_str(&format!("✓ branch {branch}\n"));
        summary.push_str("✓ files: README.md, CLAUDE.md, Cargo.toml, src/main.rs\n");
        summary.push('\n');
        summary.push_str("Jira:\n");
        for l in &jira_lines { summary.push_str(l); summary.push('\n'); }
        Ok(ToolResult::ok_text(summary).with_structured(serde_json::json!({
            "path": scaffold_dir.to_string_lossy(),
            "branch": branch,
            "jira": jira_json,
        })))
    }
}

async fn run_git(cwd: &Path, args: &[&str]) -> Result<()> {
    let out = Command::new("git").args(args).current_dir(cwd).output().await?;
    if !out.status.success() {
        return Err(Error::Other(format!(
            "git {:?}: {}",
            args,
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    Ok(())
}

fn slugify(s: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for c in s.chars().take(80) {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    while out.ends_with('-') { out.pop(); }
    if out.is_empty() { out.push_str("scaffold"); }
    out
}

fn truncate_title(s: &str, max: usize) -> String {
    if s.len() <= max { s.to_string() } else { format!("{}…", &s[..max]) }
}

fn default_stories(idea: &str) -> Vec<Value> {
    vec![
        Value::String(format!("Spike: research approach for — {idea}")),
        Value::String(format!("Scaffold repo structure for — {idea}")),
        Value::String(format!("Implement core happy path — {idea}")),
        Value::String(format!("Write tests for — {idea}")),
        Value::String(format!("Document & polish — {idea}")),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugify_works() {
        assert_eq!(slugify("Build a Perplexity clone for my homelab"), "build-a-perplexity-clone-for-my-homelab");
        assert_eq!(slugify("   !!!  "), "scaffold");
    }

    #[tokio::test]
    async fn scaffold_without_jira_still_produces_dir() {
        let dir = tempfile::tempdir().unwrap();
        let t = Scaffold { jira: None };
        let r = t
            .call(serde_json::json!({
                "idea": "widget sandbox",
                "project_key": "FLACO",
                "target_dir": dir.path().to_string_lossy(),
            }))
            .await
            .unwrap();
        assert!(r.ok, "{}", r.output);
        assert!(dir.path().join("widget-sandbox/src/main.rs").exists());
        assert!(dir.path().join("widget-sandbox/Cargo.toml").exists());
    }
}
